# Site settings
title: "2440 Festival"
email: contact@2440-festival.fr
description: "Festival d'anticipation et de cultures électroniques sur la région nantaise le 15 & 16 mai 2015. Pass 1 et 2 jours en vente dès aujourd'hui."
social_image: "http://www.2440.fr/images/social.jpg"
baseurl: ""
url: "http://www.2440.fr"

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
    - artists
    - animations
