# Site settings
title: "2440 Festival"
email: contact@2440-festival.fr
description: "Festival de Musiques Électroniques et d'Arts Numériques"
open_graph.image: "http://www.2440.fr/images/social.png"
baseurl: ""
url: "http://www.2440.fr"

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
    artists:
        output: true
